// <auto-generated />
using System;
using BookShopAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookShopAPI.Migrations
{
    [DbContext(typeof(BookShopContext))]
    partial class BookShopContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-rc.2.20475.6");

            modelBuilder.Entity("BookShopAPI.Models.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte>("AgeCategory")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Cover")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Genre")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Publication")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AgeCategory = (byte)2,
                            Author = "John Tolkien",
                            Cover = (byte)1,
                            Genre = (byte)2,
                            Publication = new DateTime(1954, 7, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings"
                        },
                        new
                        {
                            Id = 2,
                            AgeCategory = (byte)4,
                            Author = "Stephen William Hawking",
                            Cover = (byte)0,
                            Genre = (byte)1,
                            Publication = new DateTime(1988, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "A Brief History of Time"
                        },
                        new
                        {
                            Id = 3,
                            AgeCategory = (byte)1,
                            Author = "Jules Verne",
                            Cover = (byte)1,
                            Genre = (byte)2,
                            Publication = new DateTime(1870, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Twenty Thousand Leagues Under the Sea"
                        },
                        new
                        {
                            Id = 4,
                            AgeCategory = (byte)0,
                            Author = "Antoine de Saint-Exupery",
                            Cover = (byte)1,
                            Genre = (byte)1,
                            Publication = new DateTime(1943, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Little Prince"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
